name = "durable-charts"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-08"
# Add your account ID here
account_id = ""

[build.upload]
format = "modules"
dir = "src"
main = "./chart.mjs"

[durable_objects]
bindings = [
  { name = "charts", class_name = "Chart" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Chart"]
